"""
Retrieval-related constants extracted from LightRAG.
"""

GRAPH_FIELD_SEP = "<SEP>"

DEFAULT_TOP_K = 40
DEFAULT_CHUNK_TOP_K = 20
DEFAULT_MAX_ENTITY_TOKENS = 6000
DEFAULT_MAX_RELATION_TOKENS = 8000
DEFAULT_MAX_TOTAL_TOKENS = 30000
DEFAULT_COSINE_THRESHOLD = 0.2
DEFAULT_RELATED_CHUNK_NUMBER = 5
DEFAULT_KG_CHUNK_PICK_METHOD = "VECTOR"

DEFAULT_MIN_RERANK_SCORE = 0.0

DEFAULT_QUERY_PRIORITY = 5
DEFAULT_SUMMARY_PRIORITY = 8

DEFAULT_SUMMARY_LANGUAGE = "English"

DEFAULT_MAX_SECTION_CONTEXT_TOKENS = 256
DEFAULT_HEADING_LEVEL_MAX_CHARS = 80

DEFAULT_FILE_PATH_MORE_PLACEHOLDER = "truncated"
DEFAULT_MAX_FILE_PATHS = 75
